name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_v3.txt
        pip install black flake8 mypy isort
    
    - name: Run black formatter
      run: black --check src/ tests/
    
    - name: Run isort
      run: isort --check-only src/ tests/
    
    - name: Run flake8
      run: flake8 src/ tests/ --max-line-length=127 --extend-ignore=E203,W503
    
    - name: Run mypy
      run: mypy src/ --ignore-missing-imports
    
    - name: Check code complexity
      run: |
        pip install radon
        radon cc src/ --min B
